/**
 * Foursquare API Constants.
 */
app.constant('FoursquareConstants', {
    ENDPOINT: "https://api.foursquare.com/",
    VERSION: "v2",
    CLIENT_ID: "P1OHINAXZITW5Y1RX45ZPFCJ1R5ZZP5GFBGWL5GOZGMOK0WL",
    CLIENT_SECRET: "Y1XMOG02U0ZRUVNZWJCKMLKLHLL3VT2BBZ0ZAJLVE4CE2XQP",
    VERSIONING: "20181026",
    COORDINATE_SEPARATOR: ",",
    VENUES_EXPLORE: "/venues/explore"
});